/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export declare type CategoryApiQuery = 'FEATURED' | 'MINE' | 'STARRED' | 'TRENDINGS';
export declare const CategoryApiQuery: {
    FEATURED: CategoryApiQuery;
    MINE: CategoryApiQuery;
    STARRED: CategoryApiQuery;
    TRENDINGS: CategoryApiQuery;
};
