/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface ConfigurationTheme {
    /**
     * Name of the custom theme.
     */
    name?: string;
    /**
     * Logo used for the customization of the portal.
     */
    logo?: string;
    /**
     * Custom loader used for the customization of the portal.
     */
    loader?: string;
    /**
     * Path to the CSS file used for the customization of the portal.
     */
    css?: string;
}
