/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface ModelError {
    /**
     * Code of the error
     */
    code?: string;
    /**
     * Title of the error
     */
    title?: string;
    /**
     * Detail of the error
     */
    detail?: string;
}
