/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export declare type HttpMethod = 'CONNECT' | 'DELETE' | 'GET' | 'HEAD' | 'OPTIONS' | 'PATCH' | 'POST' | 'PUT' | 'TRACE' | 'OTHER';
export declare const HttpMethod: {
    CONNECT: HttpMethod;
    DELETE: HttpMethod;
    GET: HttpMethod;
    HEAD: HttpMethod;
    OPTIONS: HttpMethod;
    PATCH: HttpMethod;
    POST: HttpMethod;
    PUT: HttpMethod;
    TRACE: HttpMethod;
    OTHER: HttpMethod;
};
