/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * A notificationConfig is a generic object that can represent either a GenericNotificationConfig or a PortalNotificationConfig.
 */
export interface NotificationConfig {
    /**
     * Configuration type. Can be GENERIC, or PORTAL. Used for inheritance.
     */
    configType?: string;
    /**
     * Name of the notification config.
     */
    name?: string;
    /**
     * Type of the subject of the notification configuration. For this API, it\'s always APPLICATION.
     */
    reference_type?: string;
    /**
     * Id of the subject of the notification configuration aka application identifier.
     */
    reference_id?: string;
    /**
     * List of event that can be notified.
     */
    hooks?: Array<string>;
}
